### ISSUE TITLE
Installation fails due to conflicting openpyxl version

### ISSUE THREAD

**Issue by NeolithEra** [patarapolw/pyexcel-export#4]
Hi, users are unable to run **_pyexcel_export_** due to dependency conflict with _**openpyxl**_ package. As shown in the following full dependency graph of **_pyexcel_export_**, **_pyexcel_export_** requires **_ openpyxl >=2.5,<3.0_**，while **_pyexcel-xlsx_** requires _**openpyxl <2.6.0,>=2.5.0**_.

According to pip’s _“first found wins”_ installation strategy, _**openpyxl 2.6.4**_ is the actually installed version. However, _**openpyxl 2.6.4**_ does not satisfy _**<2.6.0,>=2.5.0**_.

### Dependency tree-----------
```
pyexcel-export - 0.3.5
| +- importlib-resources(install version:1.0.2 version range:>=1.0,<2.0)
| +- openpyxl(install version:2.6.4 version range:>=2.5,<3.0)
| | +- et-xmlfile(install version:1.0.1 version range:*)
| | | +- python(install version:2.5 version range:>=2.6.0)
| | +- jdcal(install version:1.4.1 version range:*)
| +- oyaml(install version:0.5 version range:>=0.5.0,<0.6.0)
| | +- pyyaml(install version:5.2 version range:*)
| +- pyexcel(install version:0.5.15 version range:>=0.5.8,<0.6.0)
| | +- lml(install version:0.0.9 version range:>=0.0.4)
| | +- pyexcel-io(install version:0.5.20 version range:>=0.5.19)
| | | +- lml(install version:0.0.9 version range:>=0.0.4)
| +- pyexcel-xlsx(install version:0.5.7 version range:>=0.5.6,<0.6.0)
| | +- openpyxl(install version:2.5.14 version range:>=2.5.0,<2.6.0)
| | | +- et-xmlfile(install version:1.0.1 version range:*)
| | | | +- python(install version:2.5 version range:>=2.6.0)
| | | +- jdcal(install version:1.4.1 version range:*)
| | +- pyexcel-io(install version:0.5.20 version range:>=0.5.3)
| | | +- lml(install version:0.0.9 version range:>=0.0.4)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependency to be **_openpyxl<2.6.0,>=2.5.0_**. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_pyexcel-xlsx_** to loose the version range of **_openpyxl_**.
3.	Remove your direct dependency **_openpyxl_**, and use **_openpyxl_** transitively introduced by **_pyexcel-xlsx_**.

@patarapolw Which solution do you prefer, 1, 2 or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by patarapolw** [comment]
@NeolithEra Actually, it is best to remove the upstream project; make the number of dependencies fewer is better.

**Comment by patarapolw** [comment]
I eventually chose option 1. Should be fixed now, according to Travis CI and Appveyor CI. Make it version 0.3.6.
